Iter9
25x8/metric-gathering pull request #10
Opened 2024-11-19 14:30 UTC by 25x8

2024-11-19 15:04 UTC, arttet requested changes

2024-11-19 15:04 UTC, arttet commented on cmd/server/main.go
> +		if err := s.SaveToFile(); err != nil {
[CHANGE REQUEST] Please follow the SOLID principles

2024-11-19 15:04 UTC, arttet commented on cmd/server/main.go
> +	decoder := json.NewDecoder(file)
[CHANGE REQUEST] Please follow the SOLID principles.

2024-11-19 15:04 UTC, arttet commented on cmd/server/main.go
> +func handleGetValueJSON(s *MemStorage) http.HandlerFunc {
[CHANGE REQUEST] Please split your application by Tiers.
https://medium.com/@shrestha.matina.20/what-is-the-3-tier-architecture-4520522e0720

2024-11-20 09:10 UTC, 25x8 commented on cmd/server/main.go
> +func handleUpdateMetricJSON(s *MemStorage) http.HandlerFunc {
HERE WE ARE USE MIDDLEWARES, SO IT CAN'T BE JUST METHODS

2024-11-20 11:08 UTC, arttet requested changes

2024-11-20 11:08 UTC, arttet commented on cmd/server/main.go
> +	r.Handle("/update/{type}/{name}/{value}", middleware.GzipMiddleware(logger.RequestLogger(http.HandlerFunc(h.HandleUpdateMetric)))).Methods(http.MethodPost)
[CHANGE REQUEST] Please simplify the `main` package.

2024-11-20 11:08 UTC, arttet commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
[CHANGE REQUEST] Please don't use global variables.

2024-11-20 11:08 UTC, arttet commented on internal/storage/metrics.go
> +type Metrics struct {
[CLARIFICATION] Why is it here?
[CLARIFICATION] What is it? DTO or the domain object?

2024-11-20 17:40 UTC, arttet approved these changes

2024-11-20 17:40 UTC, arttet commented on cmd/agent/senders/http_sender.go
> +		gzipWriter.Close()
[CHANGE REQUEST] Please review the Go layouts again.
https://github.com/golang-standards/project-layout/blob/master/cmd/README.md

2024-11-20 17:40 UTC, arttet commented on cmd/app/app.go
> +		panic(err)
[CHANGE REQUEST] Please don't panic
https://github.com/uber-go/guide/blob/master/style.md#dont-panic

2024-11-20 17:40 UTC, arttet commented on cmd/app/app.go
> +		os.Exit(0)
[SUGGESTION] This is not a graceful shutdown.

2024-11-20 17:40 UTC, arttet commented on internal/storage/mem_storage.go
> +func SaveToFile(s *MemStorage, filePath string) error {
[SUGGESTION] So, you can move it to another package.

2024-11-21 08:08 UTC, merged