Iter13
25x8/metric-gathering pull request #15
Opened 2024-11-22 17:29 UTC by 25x8

2024-11-25 10:14 UTC, arttet requested changes

2024-11-25 10:14 UTC, arttet commented on cmd/agent/collectors/runtime_collector.go
> +	PollCount     int64
[CHANGE REQUEST] Please move it to the `internal` package

2024-11-25 10:14 UTC, arttet commented on internal/storage/db_storage.go
> +        CREATE TABLE IF NOT EXISTS gauges (
```suggestion
        CREATE TABLE gauges (
```

2024-11-25 10:14 UTC, arttet commented on internal/storage/db_storage.go
> +        CREATE TABLE IF NOT EXISTS gauges (
[CHANGE REQUEST] Please add migrations.

2024-11-25 10:14 UTC, arttet commented on internal/storage/db_storage.go
> +	return retryOperation(context.Background(), func() error {
[CHANGE REQUEST] `Context` should be a parameter of this function.

2024-11-25 10:14 UTC, arttet commented on internal/storage/db_storage.go
> +func (s *DBStorage) Load() error {
[CHANGE REQUEST] Please remove it from the repo interface.

2024-11-25 10:14 UTC, arttet commented on internal/storage/db_storage.go
> +func (s *DBStorage) Flush() error {
[CHANGE REQUEST] Please remove it from the repo interface.

2024-11-25 10:14 UTC, arttet commented on internal/app/app.go
> +	r.Handle("/ping", middleware.GzipMiddleware(logger.RequestLogger(http.HandlerFunc(h.HandlePing)))).Methods(http.MethodGet)
[CHANGE REQUEST] Please simplify the main package.

2024-11-25 10:14 UTC, arttet commented on internal/storage/db_storage.go
> +	db, err := sql.Open("pgx", dsn)
[CHANGE REQUEST] It should not be a part of this package. You can use any connection.

2024-11-25 10:14 UTC, arttet commented on internal/storage/db_storage.go
> +	storage := &DBStorage{db: db}
[CHANGE REQUEST] Please check the connection before this.

2024-11-25 13:46 UTC, 25x8 commented on internal/storage/db_storage.go
> +        CREATE TABLE IF NOT EXISTS gauges (
убрать проверку?

2024-11-27 15:55 UTC, arttet requested changes

2024-11-27 15:55 UTC, arttet commented on cmd/agent/main.go
> +	"github.com/25x8/metric-gathering/internal/agent/collectors"
Please sort imports

2024-11-27 15:55 UTC, arttet commented on internal/agent/collectors/runtime_collector.go
> +	c.mu.Unlock()
[SUGGESTION] If I were you, I would use `defer`

2024-11-27 15:55 UTC, arttet commented on internal/agent/senders/http_sender.go
> +type Metric struct {
[SUGGESTION] It should be in the `dto` package.

2024-11-27 15:55 UTC, arttet commented on internal/agent/senders/http_sender.go
> +	resp, err := http.DefaultClient.Do(req)
[SUGGESTION] You should use `Context`

2024-11-27 15:55 UTC, arttet commented on internal/app/app.go
>  		panic(err)
[SUGGESTION] Please don't use `panic`.

2024-11-27 15:55 UTC, arttet commented on internal/handler/handler.go
> +	err = h.Storage.UpdateMetricsBatch(metrics)
[CHANGE REQUEST] We should use `Context` here.

2024-11-27 15:55 UTC, arttet commented on internal/storage/db_storage.go
> +	ctx := context.Background()
It should be a parameter of this function.

2024-11-27 15:55 UTC, arttet commented on internal/storage/db_storage.go
> +	migrations := []struct {
[CHANGE REQUEST] Please add migrations.

2024-11-27 15:55 UTC, arttet commented on internal/storage/db_storage.go
> +	migrations := []struct {
https://github.com/pressly/goose

2024-11-28 16:53 UTC, arttet commented on migrations/20241128150000_create_tables.sql
> +CREATE TABLE IF NOT EXISTS counters (
```suggestion
CREATE TABLE counters (
```

2024-11-30 11:15 UTC, merged

2025-02-22 02:28 UTC, Perederey reviewed
Привет! Ты проделал большую работу,  но не полностью реализовал требования задания. Конкретно по заданию:
- Не реализован worker pool и ограничение количества запросов через флаг -l
- Отсутствуют метрики из gopsutil

2025-02-22 02:28 UTC, Perederey commented on internal/storage/mem_storage.go
>  type MemStorage struct {
Как альтернатива, используй sync.Map вместо обычного map

2025-02-22 02:28 UTC, Perederey commented on internal/agent/collectors/runtime_collector.go
> +type MetricsCollector struct {
Раздели сбор метрик на отдельные коллекторы по типу метрик (runtime, system, custom)

2025-02-22 02:28 UTC, Perederey commented on internal/agent/collectors/runtime_collector.go
> +func (c *MetricsCollector) Collect() {
Еще не вижу тут метрики из пакета gopsutil (TotalMemory, FreeMemory, CPUutilization) 

2025-02-22 02:28 UTC, Perederey commented on cmd/agent/main.go
>  func main() {
Не совсем понял, а где worker pool? И ограничение по l? Добавь channel с буфером для ограничения количества одновременных запросов

2025-02-22 02:28 UTC, Perederey commented on internal/storage/db_storage.go
> +	ctx := context.Background()
вот тут тоже важно, используй контекст с таймаутом вместо контекста Background для операций с базой данных